import Head from 'next/head'
import QuestaoModel from '../model/questao';
import styles from '../styles/Home.module.scss'
import RespostaModel from '../model/resposta';
import { useState } from 'react';
import { useEffect } from 'react';
import Questionario from '../components/Questionario';




const questaoTeste = new QuestaoModel(1, 'As cores do padrão RGB são?', [
  RespostaModel.errada('Azul, Verde, Rosa'),
  RespostaModel.errada('Roxo, Vermelho, Branco'),
  RespostaModel.errada('Azul, Verde, Branco'),
  RespostaModel.certa('Vermelha, Verde, Azul'),
])

const BASE_URL = "http://localhost:3000/api"


export default function Home() {

  const [questao, setQuestao] = useState(questaoTeste)
  const [IdsQuestoes, setIdsQuestoes] = useState<number[]>([])

  async function carregarIdsQuestoes() {
    const resp = await fetch(`${BASE_URL}/questionario`)
    const idsDasQuestoes = await resp.json()
    console.log(idsDasQuestoes)
    setIdsQuestoes(idsDasQuestoes)
  }
  async function carregarQuestao(idQuestao: number) {
    const resp = await fetch(`${BASE_URL}/questoes/${idQuestao}`)
    const json = await resp.json()
    console.log(QuestaoModel.criarUsandoObjeto(json))
  }

  useEffect(() => {
    carregarIdsQuestoes()
  }, [])

  useEffect(() => {
    IdsQuestoes.length > 0 && carregarQuestao(IdsQuestoes[0])
  }, [IdsQuestoes])

  function questaoRespondida(questao: QuestaoModel) {

  }

  function irProximoPasso() {

  }

  return (
    <div className={styles.container}>
      <Head>
        <title>NextApp: "QUIZ"</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Proj.: "QUIZ"</h1>
      <span></span>
      <div className={styles.containerQuestoes}>
        <Questionario
          questao={questao}
          ultimaPergunta={true}
          questaoRespondida={questaoRespondida}
          irProximoPasso={irProximoPasso} />
      </div>



    </div>
  )
}
